### ISSUE TITLE
Errors prevented startup

### ISSUE THREAD

**Issue by santiagopuentep** [meteor-typescript/meteor-typescript-compiler#24] opened 2015-05-08 20:54 UTC
Hi.

I'm getting the following error when attempting to compile a test app in Windows using Node 0.12.2, Meteor 1.1.0.2 for Windows, TypeScript 1.5.0-beta:

=> Errors prevented startup:
   While building the application:
   C:\Users\Manuel\Documents\Santiago\Proyectos\Organizacion\Prototipo\zzz.ts-compiler.ts:1:1:
   module.js:338
   throw err;
   ^
   Error: Cannot find module

 'C:\Users\Manuel\Documents\Santiago\Proyectos\Organizacion\Prototipo\node_modules\typescript\bin\tsc'
   at Function.Module._resolveFilename (module.js:336:15)
   at Function.Module._load (module.js:278:25)
   at Function.Module.runMain (module.js:501:10)
   at startup (node.js:129:16)
   at node.js:814:3
=> Your application has errors. Waiting for file change.

Any ideas of what could be wrong? There's no node_modules folder in the root of my project.

**Comment by Inkp** [comment] 2015-05-10 12:42
Having exact same problem. Tried to install typescript locally, to have 'node_modules\typescript\bin\tsc'  in my project folder, but to no avail.

**Comment by shadyendless** [comment] 2015-05-10 16:18
Hey guys! Sorry, I have been pretty busy recently. I have a fix for this for people on Windows that I intend to post soon (as soon as I get the time). Please hang in there! :)

**Comment by santiagopuentep** [comment] 2015-05-10 17:03
Great, thanks!

**Comment by PharaohMaster** [comment] 2015-05-12 19:47
I too have error for tsc module, same as @santiagopuentep

**Comment by dalcib** [comment] 2015-05-31 17:36
1+

**Comment by valpet** [comment] 2015-05-31 19:14
I too get this error, how is the fix coming along? :)

**Comment by shadyendless** [comment] 2015-05-31 19:15
Going to try and have the fix up for you guys this week (and hopefully part 3)!
Sorry for the delay!



Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=pa&cv=6.3.35&pv=5.1.1]

On Sun, May 31, 2015 at 12:14 PM, Peter Valtersson < notifications@github.com [notifications@github.com] > wrote:
I too get this error, how is the fix coming along? :)

—
Reply to this email directly or view it on GitHub
[https://github.com/meteor-typescript/meteor-typescript-compiler/issues/24#issuecomment-107235712] .[https://github.com/notifications/beacon/ABGe_PcVUXG7BbLuM7E_FT7NMaU8s2gLks5oO1UDgaJpZM4EUM_4.gif]

**Comment by hkalic** [comment] 2015-06-03 21:23
tsc cannot be found. It search project folder and not the global npm package path).
I tried to copy it (node_modules) local to project folder but it return '*error TS2300: Duplicate identifier*'.

I think the problem is in first message: '*Could not find tsc binary, defaulting to 'tsc'.*'
Something is wrong with code in [**compile-tsc.js:43**](https://github.com/meteor-typescript/meteor-typescript-compiler/blob/master/plugin/compile-tsc.js)

**Comment by orefalo** [comment] 2015-06-04 00:44
Can you run tsc from the command line?

**Comment by hkalic** [comment] 2015-06-04 06:04
Yes, it works:
***C:\>tsc
Version 1.5.0-beta
Syntax:   tsc [options] [file ...]***

**Comment by valpet** [comment] 2015-06-10 17:15
Bump!
I'm sorry but I'm very eager to get started using Typescript with Meteor for a new project. Any progress on the issue? :)

**Comment by wiseguy12851** [comment] 2015-06-18 21:37
I'm also interested in a fix for this, same problem here

**Comment by divyakumarjain** [comment] 2015-06-28 13:38
+1

**Comment by shadyendless** [comment] 2015-07-09 02:16
Hey guys. This is fixed with the newest version of the typescript compiler. Navigate to your directory of your project and type `meteor update`. It should pull the latest compiler which works fine on Windows!

**Comment by mistriel** [comment] 2015-07-09 23:28
I tried that, still getting same error ...

**Comment by shadyendless** [comment] 2015-07-09 23:42
@mistriel do you have TypeScript installed for Visual Studio? NPM is wonky on Windows, so installing TS as a Visual Studio plugin appears to be the best bet for getting this to work.

**Comment by mistriel** [comment] 2015-07-09 23:45
I rather work with Webstorm, so i guess I'll install their plugin .
Thanks .

**Comment by shadyendless** [comment] 2015-07-09 23:47
You don't have to work in Visual Studio for it to work, you just need to have that plugin installed on your machine. After that, you can write your code in whichever IDE you feel like writing it in.

We can add support for more plugins, but I would need to know the path that they install to (Visual Studio's plugin always installs to the same place on all machines, so it makes it ideal to use).

**Comment by Cirych** [comment] 2015-07-23 18:02
Windows 7
node v0.12.4
npm npm@2.10.1
tsc Version 1.5.0-beta
Meteor 1.1.0.2
meteortypescript:compiler@2.0.11

Try with tsc from npm and from Visual Studio.

=> Started proxy.
=> Started MongoDB.
Could not find tsc binary, defaulting to 'tsc'.
   Building the application                  /
Compiling TypeScript os () files...
   Building the application                  |
Compiling TypeScript web.browser () files...
=> Errors prevented startup:

   While building the application:
   D:\xxx\meteor\xxx\zzz.ts-compiler.ts:1:1:
   module.js:338
   throw err;
   ^
   Error: Cannot find module 'D:\xxx\meteor\xxx\node_modules\typescript\bin\tsc'
   at Function.Module._resolveFilename (module.js:336:15)
   at Function.Module._load (module.js:278:25)
   at Function.Module.runMain (module.js:501:10)
   at startup (node.js:129:16)
   at node.js:814:3


=> Your application has errors. Waiting for file change.


On Centos all working.

**Comment by tgienger** [comment] 2015-08-02 06:44
Installed and ran great on my surface pro3. saved to repo, cloned on desktop and now I'm getting this error.

**Comment by barbatus** [comment] 2016-03-29 20:43
Issues seems to be outdated. Check out new version.

**Closed by barbatus** 2016-03-29 20:43 UTC

**Comment by aliosmanyuksel** [comment] 2016-04-03 16:28
@barbatus no, i got this error now. So i just installed about few hours ago, ran to  my computer, saved to repo, cloned to my pc and now i'm getting this error. :-1:

**Comment by barbatus** [comment] 2016-04-03 21:37
@aliosmanyuksel did you update to the last version (3.2.0)?
