### ISSUE TITLE
“ReferenceError: System is not defined” when run because transpiled class use System.

### ISSUE THREAD

**Issue by untsamphan** [meteor-typescript/meteor-typescript-compiler#40] opened 2015-11-21 18:02 UTC
Using meteortypescript:compiler 3.0.0 with Meteor 1.2.1. With or without .tsconfig, a simple ts class:-
```javascript
class Status {
};
```
transpiled to
```javascript
(function(){

/////////////////////////////////////////////////////////////////////////
//                                                                     //
// lib/Status.js                                                       //
//                                                                     //
/////////////////////////////////////////////////////////////////////////
                                                                       //
System.register("lib/Status", [], function(exports_1) {                //
    var Status;                                                        //
    return {                                                           //
        setters:[],                                                    //
        execute: function() {                                          //
            var Status = (function () {                                //
                function Status() {                                    //
                }                                                      //
                return Status;                                         //
            })();                                                      //
            ;                                                          //
        }                                                              //
    }                                                                  //
});                                                                    //
//# sourceMappingURL=Status.js.map                                     //
/////////////////////////////////////////////////////////////////////////

}).call(this);

//# sourceMappingURL=Status.js.map
```

Resulted in the error when Meteor run.

**Comment by bubuzzz** [comment] 2015-11-27 05:46
This also happened to me. It is quite weird actually, because I used the angular2-meteor package with the internal typescript compiler and there is no error about this. After that, i decided to remove the angular 2 (since it is not very mature yet) and use purely typescript with meteor and this started to appear

**Comment by ahhatem** [comment] 2015-11-27 07:32
Any update on this? I get it on standard meteor application with no angular code. Any workarounds? After adding systemjs to meteor, I am not getting and error anymore, but the templates are not loading...

**Comment by bubuzzz** [comment] 2015-11-29 22:50
I solved this problem by adding this package to meteor: `systemjs:systemjs`

**Comment by ahhatem** [comment] 2015-11-30 03:06
I also did that. But the templates  never get loaded.

**Comment by untsamphan** [comment] 2015-11-30 06:36
My workaround is to manually run tsc.
Then it seems to work fine except for source maps.

**Comment by bubuzzz** [comment] 2015-11-30 07:01
the problem is with the systemjs package, you have to include the js file in order to let it load (https://github.com/systemjs/systemjs#browser) this is a suggestion from (http://stackoverflow.com/questions/33991506/meteor-methods-cannot-be-added-during-run-time-when-using-typescript-with-system). However, it would be better to ignore the systemjs if you don't want to use it and set the module to "none" in the `.tsconfig`. Check out  that file from the sample folder

**Comment by barbatus** [comment] 2016-03-28 21:02
Prerequisite for setting `module:system` is to have `systemjs:systemjs` installed.
Otherwise, I don't see why it may be an issue any more. Closing.

**Closed by barbatus** 2016-03-28 21:02 UTC
